default_language_version:
  python: python3

repos:
  # Run fast code improvement/checks before running PR specific helpers.
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: 'mvesuvio/vesuvio_analysis/scribles|mvesuvio/experiments/original_inputs|mvesuvio/original_inputs.py|unpackaged'
        types: ['python']
      - id: check-added-large-files
        args: ['--maxkb=4096']
        exclude: 'mvesuvio/experiments/original_inputs|unpackaged'

  - repo: https://github.com/PyCQA/flake8.git
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--config', 'config.flake8']
        exclude: 'mvesuvio/vesuvio_analysis/scribles|mvesuvio/experiments/original_inputs|mvesuvio/original_inputs.py|unpackaged'
