default_language_version:
  python: python3

repos:
  # Run fast code improvement/checks before running PR specific helpers.
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: 'vesuvio_analysis/scribles|experiments/original_inputs|original_inputs.py'
        types: ['python']
      - id: check-added-large-files
        args: ['--maxkb=4096']
        exclude: experiments/original_inputs

  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--config', 'config.flake8']
        exclude: 'vesuvio_analysis/scribles|experiments/original_inputs|original_inputs.py'
