default_language_version:
  python: python3

repos:
  # Run fast code improvement/checks before running PR specific helpers.
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=4096']

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
      - id: autopep8
        args: ['--in-place --aggressive --aggressive -']

  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--extend-ignore=E999,F821,E127']
