default_language_version:
  python: python3

repos:
  # Run fast code improvement/checks before running PR specific helpers.
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: .patch$|experiments/original_inputs|original_inputs.py
      - id: check-added-large-files
        args: ['--maxkb=4096']
        exclude: experiments/original_inputs

  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        exclude: vesuvio_analysis/scribles|experiments/original_inputs|original_inputs.py
        args: ['--ignore=E114,E115,E116,E121,E123,E126,E133,E2,E704,E722,E741,E743,W503,F403,F405,F9996','--max-line-length=140']