name: vesuvio-env

channels:
  - conda-forge
  - mantid

dependencies:
  - flake8
  - conda-wrappers
  - pre-commit==2.15 #review this
  - coverage
  - mantid==6.7.0 #review this
  - matplotlib
  - iminuit
  - h5py
  - mock
  - jacobi==0.4.2 #pinned until newer versions functionality confirmed