name: vesuvio-env

channels:
  - conda-forge
  - mantid

dependencies:
  - python==3.8.* #Upgrade to python 3.10
  - flake8
  - conda-wrappers
  - pre-commit==2.15 #review this
  - coverage
  - mantid>=6.7
  - matplotlib
  - iminuit
  - h5py
  - mock
  - jacobi==0.4.2 #pinned until newer versions functionality confirmed