- name: Deploy dockerized github runner
  community.docker.docker_container:
    name: "{{ runner_name }}"
    image: ubuntu:focal-20231128
    detach: yes
    init: yes
    network_mode: host
    recreate: yes
    pull: yes
    shm_size: 512M