- name: Copy setup script to host
  copy: 
    src: setup/setup.sh
    dest: /tmp/setup.sh
    mode: '0755'

- name: Deploy dockerized github runner
  community.docker.docker_container:
    name: "{{ runner_name }}"
    image: ubuntu:focal-20231128
    detach: yes
    init: yes
    network_mode: host
    recreate: yes
    pull: yes
    shm_size: 512M
    volumes:
      - /tmp/setup.sh:/home/setup.sh
    command: /home/setup.sh

- name: Remove setup script
  ansible.builtin.file:
    path: /tmp/setup.sh
    state: absent
