name: EVSVesuvio pull request workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up conda environnment
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: vesuvio-env
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      # Runs flake8
      - name: Flake8
        run: python -m flake8 --config=config.flake8

      # Runs Unit tests
      #- name: Run EVSVesuvio Analysis Unit Tests
      #  run: coverage run -m unittest discover -s ./EVSvesuvio/vesuvio_analysis

      # Runs System tests
      #- name: Run EVSVesuvio Analysis System Tests
      #  run: python -m unittest discover -s ./EVSVesuvio/system_tests

      - name: Run EVSVesuvio Calibration Unit Tests
        if: always()
        run: python -m unittest discover -s ./unpackaged/vesuvio_calibration/tests/unit

      - name: Run Vesuvio Calibration System Tests
        if: always()
        run: python -m unittest discover -s ./unpackaged/vesuvio_calibration/tests/system

      # Report coverage
      #- name: Report Coverage
      #  run: coverage report